version: '3'
services:
  mysql-db:
    container_name: mysql-db
    env_file:
      - .env
    image: "mysql:latest" 
    ports:
      - "3307:3306"
    networks:
      springboot-mysql-network:
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - ./mysql-data:/var/lib/mysql:rw
        - ./mysql-init:/docker-entrypoint-initdb.d/:ro
        
  springboot-mysql-app:
    container_name: springboot-mysql-app
    image: springboot-mysql-app:latest
    build: 
      context: ./air-companies-management-system
      dockerfile: Dockerfile
    working_dir: /air-companies-management-system
    restart: on-failure
    volumes:
      - ./opt/app:/app
#      - C:/Users/Admin/.m2:/root/.m2
    ports:
      - "8088:8080"
    depends_on: 
      - mysql-db
    networks: 
      springboot-mysql-network: 
    environment:      
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}    
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/${MYSQL_DB}?useSSL=false&allowPublicKeyRetrieval=true
    command: mvn clean spring-boot:run
    
networks:
    springboot-mysql-network: